version: '3'
services:
  # web:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - db
  #   depends_on:
  #     - db
  db:
    image: mongo:5.0.0
    container_name: db-tattuo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db

# To mount the container from the terminal run:
# docker-compose up -d
